name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          scope: '@foo-software'
      - name: Install
        run: |
          npm install lerna -g
          lerna bootstrap --hoist
      - name: Publish Packages
        run: |
          node packages/reach-charts-ci-tools/dist/bin/publish-packages.js
